version: "3.8"

services:
  web:
    container_name: rest-api
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "5000:5000"
    # volumes:
    #   - ./:/app

networks:
  web_api:
    driver: bridge
