version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: api_redis
    ports:
      - "6379:6379"
    # restart: always
    networks:
      - web_api

  postgesql:
    image: postgres:latest
    container_name: api_postgesql
    ports:
      - "5432:5432"
    # restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - web_api
  jaeger:
    container_name: jaeger_container
    # restart: always
    image: jaegertracing/all-in-one:latest
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    networks:
      - web_api

networks:
  web_api:
    driver: bridge
