server:
  AppVersion: 1.0.0
  Port: :5000
  Mode: Development
  JwtSecretKey: secret
  CtxDefaultTimeout: 12
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: true
  Encoding: console
  Level: debug

metrics:
  URL: 0.0.0.0:7070
  ServiceName: api

jaeger:
  Host: localhost:6831
  ServiceName: REST_API
  LogSpans: false
