basePath: /api/v1
info:
  contact:
    email: ducpx96@gmail.com
    name: Duc PX
    url: https://github.com/ducpx
  description: Golang REST API
  title: Go Learn REST API
  version: "1.0"
paths: {}
swagger: "2.0"
